services:
  db:
    image: postgres:16-bullseye
    container_name: pgsql
    hostname: pgsql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  db_volume: